function(SetCompileOptionsLibC target)
    target_compile_options(${target} PRIVATE 
                        -std=c11
                        -Wall
                        -Werror
                        -Wextra
                        -fpic
                        -fvisibility=hidden
                        -fstrict-aliasing
                        -fomit-frame-pointer
                        -m64)
    target_link_options(${target} PRIVATE -rdynamic)
    if (${BS_ENABLE_GCOV})
        message(STATUS "Gcov enabled")
        target_compile_options(${target} PRIVATE -fprofile-arcs -ftest-coverage)
    endif()
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        message(STATUS "Debug type")
        if (${BS_ENABLE_ASAN})
            message(STATUS "Enable Asan")
            target_link_options(${target} PRIVATE -fsanitize=address)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(STATUS "Disable Asan")
        endif()
        target_compile_options(${target} PRIVATE -g3 -fsanitize=undefined -O0)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    else()
        if (${REL_WITH_DEBUG_INFO})
            message(STATUS "Enable debug info in Release mode")
            target_compile_options(${target} PRIVATE -g3)
        endif()
        message(STATUS "Release type")
        target_compile_options(${target} PRIVATE
                        -O2
                        -ffast-math
                        -mavx2
                        -march=corei7
                        -mtune=corei7
                        -funroll-loops
                        -flto)
        if (${BS_ENABLE_PROFILING})
            find_library(MEMPROF_LIB memprof)
            if(MEMPROF_LIB)
                message(STATUS "Memprofile lib founded")
                target_link_libraries(${target} PRIVATE ${MEMPROF_LIB})
                if (${BS_USE_PROFILE})
                    target_compile_options(${target} PRIVATE  -fmemory-profile-use=${CMAKE_CURRENT_BINARY_DIR})
                else()
                    target_compile_options(${target} PRIVATE -fmemory-profile=${CMAKE_CURRENT_BINARY_DIR})
                endif()
            else()
                message(STATUS "Memprofile not founded")
            endif()

            if (${BS_USE_PROFILE})
                message(STATUS "Using profile")
                target_compile_options(${target} PRIVATE -fprofile-use=${CMAKE_CURRENT_BINARY_DIR})
            else()
                message(STATUS "Generate profile")
                target_compile_options(${target} PRIVATE -fprofile-generate=${CMAKE_CURRENT_BINARY_DIR})
                target_link_options(${target} PRIVATE -fprofile-generate=${CMAKE_CURRENT_BINARY_DIR})
            endif()
        endif()
        if (!${BS_DISABLE_PERF})
            message(STATUS "Using perf")
            target_link_options(${target} PRIVATE -flto)
        else()
            message(STATUS "No perf support")
        endif()
    endif()
endfunction()

function(SetCompileOptionsC target)
    target_compile_options(${target} PRIVATE 
                        -std=c11
                        -Wall
                        -Werror
                        -Wextra
                        -fstrict-aliasing
                        -m64)
    if (${BS_ENABLE_GCOV})
        message(STATUS "Gcov enabled")
        target_compile_options(${target} PRIVATE -fprofile-arcs -ftest-coverage)
    endif()
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        message(STATUS "Debug type")
        if (${BS_ENABLE_ASAN})
            message(STATUS "Enable Asan")
            target_compile_options(${target} PRIVATE -fsanitize=address)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(STATUS "Disable Asan")
        endif()
        target_compile_options(${target} PRIVATE -g3 -fsanitize=undefined -O0 -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    else()
        if (${REL_WITH_DEBUG_INFO})
            target_compile_options(${target} PRIVATE -g3)
        endif()
        message(STATUS "Release type")
        target_compile_options(${target} PRIVATE
                        -O3
                        -ffast-math
                        -mavx2
                        -march=corei7
                        -mtune=corei7
                        -funroll-loops
                        -flto)
        target_link_options(${target} PRIVATE -flto)
    endif()
endfunction()

function(SetCompileOptionsCXX target)
    target_compile_options(${target} PRIVATE -std=c++20)
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        message(STATUS "Debug type")
        if (${BS_ENABLE_ASAN})
            message(STATUS "Enable Asan")
            target_compile_options(${target} PRIVATE -fsanitize=address)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(STATUS "Disable Asan")
        endif()
        target_compile_options(${target} PRIVATE -g3 -fsanitize=undefined -O0 -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    else()
        if (${REL_WITH_DEBUG_INFO})
            target_compile_options(${target} PRIVATE -g3)
        endif()
        message(STATUS "Release type")
        target_compile_options(${target} PRIVATE -O2 -flto -mavx2 -march=corei7 -mtune=corei7)
        target_link_options(${target} PRIVATE -flto)
    endif()
endfunction()

function(SetCompileOptionsFuzzCXX target)
    target_compile_options(${target} PRIVATE -std=c++20 -fsanitize=fuzzer-no-link)
    target_link_options(${target} PRIVATE -fsanitize=fuzzer-no-link)
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        message(STATUS "Debug type")
        if (${BS_ENABLE_ASAN})
            message(STATUS "Enable Asan")
            target_compile_options(${target} PRIVATE -fsanitize=address)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(STATUS "Disable Asan")
        endif()
        target_compile_options(${target} PRIVATE -g3 -fsanitize=undefined -O0 -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    else()
        if (${REL_WITH_DEBUG_INFO})
            target_compile_options(${target} PRIVATE -g3)
        endif()
        message(STATUS "Release type")
        target_compile_options(${target} PRIVATE -O2 -flto -mavx2 -march=corei7 -mtune=corei7)
        target_link_options(${target} PRIVATE -flto)
    endif()
endfunction()

function(GlobalCompileOptionsCXX)
    add_definitions(-D_XOPEN_SOURCE=700)
    if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
        message(STATUS "Debug type")
        if (${BS_ENABLE_ASAN})
            message(STATUS "Enable Asan")
            add_compile_options(-fsanitize=address)
            add_link_options(-fsanitize=address)
        else()
            message(STATUS "Disable Asan")
        endif()
        add_compile_options(-g3 -fsanitize=undefined -O0 -fno-omit-frame-pointer)
        add_link_options(-fsanitize=undefined)
    else()
        if (${REL_WITH_DEBUG_INFO})
            add_compile_options(-g3)
        endif()
        message(STATUS "Release type")
        add_compile_options(-O2 -flto -mavx2 -march=corei7 -mtune=corei7)
        add_link_options(-flto)
    endif()
endfunction()